config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
 
  resources :selections
  root to: 'folders#index'
  resources :folders do
    resources :documents
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
    has_many :documents, dependent: :destroy
    belongs_to :user
    validates :name, presence: true
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  # GET /folders
  def index
    @folders = current_user.folders.all
  end

  # GET /folders/new
  def new
    @folder = current_user.folders.new
  end

  # POST /folders
  def create
    @folder = current_user.folders.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.js
        format.html { redirect_to folder_url }
        format.json { head :no_content }
      else
        format.js { render 'errors.js.erb' }
        # format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @folder.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to folders_url }
      format.json { head :no_content }
    end
  end
  
  # def edit
  # end
  
  # def show
  # end
  
  # def update
  #   respond_to do |format|
  #     if @folder.update(folder_params)
  #       format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @folder }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @folder.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  private
    def set_folder
      @folder = Folder.find(params[:id])
    end

    def folder_params
      params.require(:folder).permit(:name)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_folder.html.erb
<div class="folder" id="<%= folder.id %>">
    <div class="folder-bar d-flex flex-row">
        <div class="align-bottom styled-checkbox">
            <input type="checkbox" class="checkbox" id="checkbox<%= folder.id %>">
        </div>
        <div class="card folder-card flex-grow-1">
            <div class="card-header collapsed d-flex flex-row" role="button" data-toggle="collapse" data-target="#collapse<%= folder.id %>" aria-expanded="true" aria-controls="collapse<%= folder.id %>">
                <div class="folder-name white flex-grow-1">
                    <%= folder.name %>
                </div>
                <div>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                        <path
                            fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"
                        />
                    </svg>
                </div>
            </div>
        </div>
        <div class="folder-icons">
            <div>
                <%= link_to new_folder_document_path(folder), remote: true, id: "documentButton", class: "add-doc ml-2" do %>
                    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-file-earmark-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M9 1H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h5v-1H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5v2.5A1.5 1.5 0 0 0 10.5 6H13v2h1V6L9 1z"/>
                        <path fill-rule="evenodd" d="M13.5 10a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13v-1.5a.5.5 0 0 1 .5-.5z"/>
                        <path fill-rule="evenodd" d="M13 12.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
                    </svg>
                <% end %>
            </div>
            <div>
                <%= link_to folder, method: :delete, remote: true, id: "#{folder.id}", class: "delete-folder ml-2" do %>
                    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path 
                            d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
                        />
                        <path
                            fill-rule="evenodd"
                            d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                        />
                    </svg>
                <% end %>
            </div>
        </div>
    </div>
    
    <div id="collapse<%= folder.id %>" class="collapse px-1 px-sm-2 px-md-5" aria-labelledby="heading<%= folder.id %>" data-parent="#accordion">
        <div class="card-body folder-contents">
            <div id="folderDocs<%= folder.id %>">
                <% if folder.documents.any? %>
                    <%= render folder.documents %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/folders/_form.html.erb
<div id="folderModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg" role="content">
    <div class="modal-content rounded-0 border-0">
      <div class="modal-header rounded-0">
        <h4 class="modal-title">Add Folder</h4>
        <button type="button" class="close" data-dismiss="modal">
            &times;
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: folder, id: "newFolderForm", autocomplete: "off") do |form| %>
          <div class="d-flex flex-sm-row flex-column" id="name">
            <%= form.label :name, class: "my-0", style: "width: 3rem;" %>
            <%= form.text_field :name, class: "styled-input flex-grow-1" %>
          </div>
          <div class="text-right errors name-errors"></div>
          <div class="d-flex flex-row justify-content-end">
            <%= form.submit nil, class: "styled-btn mt-2" %>
          </div>
        <% end %>
      </div> <!-- end of modal body -->
    </div> <!-- end of modal content -->
  </div> <!-- end of dialog -->
</div> <!-- end of modal -->

app/views/folders/create.js.erb
$('#folderModal').modal('hide');
$('#accordion').append("<%= j render @folder %>")
$('.alert-text').text("Folder created successfully");
$('.alert-text').fadeIn();

app/views/folders/destroy.js.erb
$('.delete-folder').bind('ajax:success', function() {
    let folderId = '#' + $(this).attr("id");
    
    var newSelectees = selectees.filter(s => s !== $(this).attr('id'));
    selectees = newSelectees;
            
    $(folderId).fadeOut(500, function() {
        $(this).remove();
    });
    $('.alert-text').text("Folder successfully deleted");
    $('.alert-text').fadeIn();
});

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/errors.js.erb
$('.name-errors').html("<%= j @folder.errors[:name].join('<br>') %>")

app/views/folders/index.html.erb
<div class="container">
  <div class="sub-heading">Folders</div>
  <div id="accordion">
      <%= render @folders %>
  </div>
  <div id="selection"></div>
  <div id="new-folder"></div>
  <div id="new-doc"></div>
  <div id="newSelection"></div>
</div>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Back', folders_path %>

app/views/folders/new.js.erb
$('#new-folder').html("<%= j render 'form', folder: @folder %>")
$('#folderModal').modal('show');
$('.text-field').val('');

  

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="Folder">
  <%= content_tag :span, "#{@folder.name}", class: "folder-name" %>
  <%= link_to 'Edit', edit_folder_path(@folder) %>
</div>

<div id="documents">
  <%= render @folder.documents %>
</div>

<div>
  <%= form_for([@folder, @folder.documents.new]) do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="actions">
      <%= f.submit "Add new document" %>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>