config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
 
  resources :selections
  root to: 'folders#index'
  resources :folders do
    resources :documents
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<div class="alert">
  <div class="container">
    <div class="d-flex flex-row">
      <div class="alert-text">
        <% if flash.any? %>
          <% flash.each do |type, msg| %>
            <%= msg %>
          <% end %>
        <% end %>
      </div>
      <% if logged_in? %>
        <div class="d-block d-md-none ml-auto">
          <%= link_to "Logout", logout_path, method: :delete, class: "logout-btn" %> 
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_head.html.erb
<head>
  <title>WordFrequencyComparator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="robots" content="noindex">
  <link rel="icon" href="<%= asset_path("doc.png") %>">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>

app/views/shared/_header.html.erb
<header>
  <div class="header">
    <div class="container">
      <div class="d-flex flex-row justify-content-between">
        <a href="#" class="pb-3 pt-3">
          <div class="d-flex flex-row align-items-center">
            <div>
              <img src="<%= asset_path("doc.png") %>" height="40" width="40" class="align-top">
            </div>
            <div class="main-heading px-1 flex-sm-column">
              <div>
                <span class="green">Word</span><span class="white">Frequency</span><span class="green">Comparator</span>
              </div>
            </div>
          </div>
        </a>
        <div class="login d-flex flex-row pt-2">
          <% if logged_in? %>
              <div class="d-none d-md-block">
                <span class="green">Logged in as </span><span class="white"><%= current_user.username %></span>
              </div>
              <div class="d-none d-md-block">
                <%= link_to "Logout", logout_path, method: :delete, class: "ml-1 logout-btn" %> 
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light py-0 menu">
  <div class="container">
    <% if logged_in? %>
    <ul class="navbar-nav flex-row mx-auto">
      <li class="menu-item">
        <%= link_to new_folder_path, remote: true, id: "folderButton", class: "menu-link" do %>
          <div class="text-center px-3 py-2 py-sm-3">
            New Folder
          </div>
        <% end %>
      </li>
      <li class="menu-item">
        <%= link_to new_selection_path, remote: true, id: "compareBtn", class: "menu-link" do %>
          <div class="nav-item text-center px-3 py-2 py-sm-3">
            New Comparison 
          </div>
        <% end %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>