config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
 
  resources :selections
  root to: 'folders#index'
  resources :folders do
    resources :documents
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :user
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections
  # POST /selections.json
  def create
    
    if params[:selectees_array]
      @selection = Selection.new(user: current_user)
      JSON.parse(params[:selectees_array]).each do |selectee|
        @selection.selectees << selectee
      end
      
      @selection.save!
      redirect_to folders_url
    else
      @selection = Selection.last
      @selection.update(selection_params)
      @selection.save!
      
      if @selection.save
        @selection.selectees.each do |selectee|
         
          folder = Folder.find(selectee)
          folder_hash = {folder_id: folder.id, "name": folder.name, "docs": []}
          folder.documents.search(@selection.word).with_pg_search_highlight.each do |doc|
            folder_hash[:docs].push({"doc_id": doc.id, "title": doc.title, "highlights": doc.pg_search_highlight, "tally": doc.pg_search_highlight.split('<br>').length})
          end
          folder_tally = folder_hash[:docs].map{|doc| doc[:tally]}.sum
          folder_hash.store("tally", folder_tally)
          folder_hash.store("average", folder_tally.to_f / folder.documents.count)
          @selection.selectees_json.push(folder_hash)
        end
        
        @selection.save
        
        respond_to do |format|
            format.js
            format.html { redirect_to folders_url }
            format.json { head :no_content }
        end
      else
        redirect_to folders_url, alert: "Unable to perform comparison"
      end
    end
  end

  # PATCH/PUT /selections/1
  # PATCH/PUT /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { render :show, status: :ok, location: @selection }
      else
        format.html { render :edit }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def selection_params
      params.require(:selection).permit(:new, :create, :show, :index, :destroy, :selectees, :word)
    end
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/views/selections/_form.html.erb
<div id="selectionModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg" role="content">
    <div class="modal-content rounded-0 border-0">
      <div class="modal-header rounded-0">
        <h4 class="modal-title">Enter Word</h4>
        <button type="button" class="close" data-dismiss="modal">
            &times;
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(@selection, :remote => true, autocomplete: "off") do |f| %>
          <div class="d-flex flex-sm-row flex-column">
            <%= f.label :word, class: "my-0", style: "width: 3rem;" %>
            <%= f.text_field :word, class: "styled-input flex-grow-1" %>
          </div>
          <div class="d-flex flex-row justify-content-end">
            <%= f.submit "Proceed to comparison", id: "submitFor#{@selection.id}", class: "styled-btn mt-2", data: {disable_with: "Comparing..."}, style: "width: 12rem;" %>
          </div>
        <% end %>
      </div> <!-- end of modal body -->
    </div> <!-- end of modal content -->
  </div> <!-- end of dialog -->
</div> <!-- end of modal -->

app/views/selections/_selection.html.erb
<div class="pb-4">
    <div class="sub-heading mb-3">
        Results of Comparison for "<%= selection.word %>"
    </div>
    
    <div class="selectees">
        <% selection.selectees_json.each do |selectee| %>
            <div class="selectee d-flex flex-column align-items-stretch">
                <div class="overflow-hidden flex-1"><%= selectee["name"] %></div>
                <div class="mb-1 flex-1">Average frequency: <%= selectee["average"] %></div>
                <% if selectee["average"] > 0.0 %>
                    <div id="chart_<%= selectee["folder_id"] %>" class="chart"></div>
                <% end %>
                <div class="d-flex flex-row justify-content-end mt-1">
                    <a class="highlights-btn" data-toggle="modal" data-target="#modal_<%= selectee["folder_id"] %>">
                        View Highlights
                    </a>
                </div>
            </div>
        <% end %>
    </div>
    
    <script type="text/javascript">
    
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawCharts);
        
        function drawCharts() {
            <% selection.selectees_json.each do |selectee| %>
                var data = new google.visualization.DataTable();
                data.addColumn('string', 'Documents');
                data.addColumn('number', 'Frequency');
                <% selectee["docs"].sort_by{|doc| doc["tally"]}.each do |doc| %>
                    data.addRows([
                        ['<%= doc["title"] %>', <%= doc["tally"] %>]
                    ]);
                    var options = {
                        'title': '<%= selectee["name"] %>', 
                        colors: ['#0277bc'],
                        legend: {position: 'in'}
                    };
                
                    var chart = new google.visualization.ColumnChart(document.getElementById('chart_<%= selectee["folder_id"] %>'));
                    chart.draw(data, options);
                <% end %>
            <% end %>
        }
        
    </script>
        
    <% selection.selectees_json.each do |selectee| %>
        <div id="modal_<%= selectee["folder_id"] %>" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg" role="content">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title"><%= selectee["name"] %></h4>
                        <button type="button" class="close" data-dismiss="modal">
                            &times;
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-2 highlights">
                            <% selectee["docs"].each do |doc| %>
                                <%= doc["title"] %>
                                <p class="pl-2 mt-2">
                                    <%= doc["highlights"].html_safe %>
                                </p>
                            <% end %>
                        </ul>
                    </div> <!-- end of modal body -->
                </div> <!-- end of modal content -->
            </div> <!-- end of dialog -->
        </div> <!-- end of modal -->
    <% end %>
</div>

app/views/selections/create.js.erb
$('#selectionModal').modal('hide');
$('#selection').html("<%= j render @selection %>")
$('.alert-text').text("Comparison completed successfully");
$('html, body').animate({scrollTop: $('#selection').offset().top}, 2000);

app/views/selections/edit.html.erb
<h1>Editing Selection</h1>

<%= render 'form', selection: @selection %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Selections</h1>

<table>
  <thead>
    <tr>
      <th>New</th>
      <th>Create</th>
      <th>Show</th>
      <th>Index</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= selection.new %></td>
        <td><%= selection.create %></td>
        <td><%= selection.show %></td>
        <td><%= selection.index %></td>
        <td><%= selection.destroy %></td>
        <td><%= link_to 'Show', selection %></td>
        <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
        <td><%= link_to 'Destroy', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.js.erb
$('#newSelection').html("<%= j render 'form' %>")
$('#selectionModal').modal('show');
$('.text-field').val('');

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>New:</strong>
  <%= @selection.new %>
</p>

<p>
  <strong>Create:</strong>
  <%= @selection.create %>
</p>

<p>
  <strong>Show:</strong>
  <%= @selection.show %>
</p>

<p>
  <strong>Index:</strong>
  <%= @selection.index %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @selection.destroy %>
</p>

<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>